# Generated by Django 3.0.4 on 2020-06-25 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link_short', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
