# Generated by Django 3.0.4 on 2020-06-25 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link_short', '0003_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Persons',
        ),
    ]
